---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
  namespace: default
spec:
  selector:
    matchLabels:
      app: game-2048
  replicas: 2
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
      - name: game-2048
      image: mohammadathar/2048-game
      ports:
      - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: game
  namespace: default
  labels:
    app: game-2048
spec:
  selector:
    app: game-2048
    type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP 
